# Generated by Django 4.0.4 on 2022-05-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(default='Pending', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Make_Template',
        ),
    ]
