# Generated by Django 4.0.4 on 2022-05-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='farmer',
            field=models.TextField(null=True),
        ),
    ]
